### ISSUE TITLE
ksh completions

### ISSUE THREAD

**Issue by rjc** [qbit/dotfiles#1]
Hi,

Like most people, I had no idea about `KSH` completions!

Thanks for the [write-up](https://deftly.net/posts/2017-05-01-openbsd-ksh-tab-complete.html)!

I had a quick look at your list and a couple of things, which you may find helpful :^), come to mind:

- you can drop `cat` ;^) from the `ssh` completion and use something like:

        $(awk '{ print $1 }' ~/.ssh/known_hosts | cut -d, -f1)

to ensure the lines beginning with `hostname,ip_address` still work.

- some (most?) of your completions should have `complete_command_1` rather than just `complete_command` - otherwise you're running into an issue where, i.e. `console` is listed as any argument to `vmctl`, not just the first one. The same goes for `mpc`, `git`, etc.

Regards,

rjc

**Comment by qbit** [comment]
Thanks or the feedback! I have a long habit of useless use of cat, probably because I typically cat the file first to see what I should be awk'ing.

I am gonna go with a full awk on the `ssh` completion:
```
awk '{split($1,a,","); print a[1]}' ~/.ssh/known_hosts
```
For the `_1` stuff, I haven't sorted them out properly yet (doing it as I get annoyed by commands I run), but the main goal is to be able to do things like `vmctl -c start vm`, `vmctl start -c vm`..
